loop create
set int state loop0 up

clear trace
trace add pg-input 100

packet-generator new {				\
  name udp							\
  limit 10							\
  rate 1e4							\
  node ethernet-input				\
  interface loop0					\
  size 100-100						\
  worker 1							\
  data {							\
    IP4: 1.2.3 -> 4.5.6 vlan 1					\
    UDP: 192.168.1.2 - 192.168.2.255 -> 192.168.1.1		\
    UDP: 4321 -> 1234						\
    length 72							\
    incrementing 100						\
  }								\
}

set interface detunnel loop0 arc device-input
packet-generator enable
show packet-generator