loop create
set int state loop0 up

clear trace
trace add pg-input 100

packet-generator new {				\
  name udp							\
  limit 49546457546					\
  node ethernet-input				\
  interface loop0					\
  size 100-100						\
  worker 1							\
  data {							\
    IP4: 1.2.3 -> 4.5.6 vlan 1					\
    UDP: 192.168.1.1 - 192.170.10.255 -> 10.18.1.1 - 10.20.10.255		\
    UDP: 1110 - 1115 -> 3000 - 3027						\
    length 72							\
    incrementing 100						\
  }								\
}

set interface detunnel loop0 arc device-input
packet-generator enable
show packet-generator